- .github/workflows/main.yml
- package.json
- src/commands/addSessionCommand.ts
- src/commands/refreshCommand.ts
Adding auto-updates for the vsix file when a PR pushes to main
> 19 gh actions

- .github/workflows/main.yml
Signed-off-by: AndrewTwydell <u1858490@unimail.hud.ac.uk>
> add compile to gh actions

- .github/workflows/main.yml
Signed-off-by: AndrewTwydell <u1858490@unimail.hud.ac.uk>
> add continue on error for compile errors

- src/trees/treeProvider.ts
Signed-off-by: AndrewTwydell <u1858490@unimail.hud.ac.uk>
> Added IGZ* and removed debug code

- package.json
- src/commands/disableProgramCommand.ts
- src/commands/enableProgramCommand.ts
- src/commands/newCopyCommand.ts
- src/extension.ts
- src/trees/CICSProgramTree.ts
- src/trees/treeProvider.ts
This adds an Enable / Disable feature to programs on the right-click context menu. 
It sets the STATUS of a program to Enabled or Disabled and refreshes the tree view accordingly.
> 24 enable disable

- src/commands/filterProgramsCommand.ts
- src/trees/treeProvider.ts
Resolves #41.
Simple PR to add descriptions to Input boxes and Quick Pick Dropdowns. 
Improves user experience.
> Descriptions for filter and add session

- src/trees/webviewHTML.ts
Resolves #38.
This PR updates the UI of the form that creates profiles. 
It uses IBM's Carbon Styling elements, and groups together the different groups of details (Connection details, user details, cics details)
> Updated UI of new profile form

- README.md
- src/commands/newCopyCommand.ts
- src/commands/phaseInCommand.ts
Signed-off-by: Joe-Winchester <winchest@uk.ibm.com>
> Readme.md includes newcopy and show attributes content

- README.md
Signed-off-by: Joe-Winchester <winchest@uk.ibm.com>
> Fixed graphic on newcopy gif

- package.json
- src/commands/newCopyCommand.ts
- src/trees/treeProvider.ts
There were references to sessions which have been changed to profiles.
We have also removed excess messages.
> Updating session references to profile

- resources/conformance/test_evaluation_guide_table.md
Signed-off-by: Joe-Winchester <winchest@uk.ibm.com>
> Upload the .md file with the Zowe Explorer conformance criteria

- package.json
- src/extension.ts
- src/trees/CICSLocalFileTree.ts
- src/trees/CICSPlexTree.ts
- src/trees/CICSProgramTree.ts
- src/trees/CICSTransactionTree.ts
Show previously applied filters after collapsing and expanded lazily loaded plex
> Store resource filter

- src/commands/filterAllProgramsCommand.ts
- src/commands/filterAllTransactionsCommand.ts
- src/commands/filterLocalFileCommand.ts
- src/commands/filterProgramsCommand.ts
- src/commands/filterTransactionCommand.ts
- src/commands/getFilterAllLocalFilesCommand.ts
- src/commands/getFilterPlexResources.ts
- src/utils/FilterUtils.ts
- src/utils/getDefaultProgramFilter.ts
- src/utils/getDefaultTransactionFilter.ts
- src/utils/getIconPath.ts
> Consistent filtering

- src/trees/CICSRegionsContainer.ts
- src/utils/FilterUtils.ts
> Fix regions container filter label

- src/trees/CICSTree.ts
> Closes #166; continue if name doesn't exist

- src/commands/deleteSessionCommand.ts
- src/commands/updateSessionCommand.ts
Delete profile command triggers the opening of the config file
> Next delete profile cmd

- package.json
- src/extension.ts
Remove refresh icon from CICS view for first TP1 release
> Next remove refresh icon

- docs/Early access - Using Team Configuration.md
> add early access doc

- src/extension.ts
- src/utils/workspaceUtils.ts
> Next require ze v2

- package.json
> Add build script for windows

- package.json
- src/commands/refreshCommand.ts
- src/extension.ts
- src/trees/CICSCombinedLocalFileTree.ts
- src/trees/CICSCombinedProgramTree.ts
- src/trees/CICSCombinedTransactionTree.ts
- src/trees/CICSLocalFileTree.ts
- src/trees/CICSProgramTree.ts
- src/trees/CICSTransactionTree.ts
- src/trees/CICSTree.ts
- src/utils/expansionHandler.ts
- src/utils/profileManagement.ts
> Next refresh view

- src/trees/CICSSessionTree.ts
- src/trees/CICSTree.ts
- src/utils/profileUtils.ts
> Next prompt credentials

- src/commands/updateSessionCommand.ts
> Use getLoadedProfConfig for upate cmd

- package-lock.json
- package.json
- src/commands/deleteSessionCommand.ts
- src/commands/refreshCommand.ts
- src/commands/updateSessionCommand.ts
- src/extension.ts
- src/trees/CICSTree.ts
- src/utils/expansionHandler.ts
- src/utils/profileManagement.ts
> Next testing new profilescache

- src/commands/deleteSessionCommand.ts
- src/commands/refreshCommand.ts
- src/trees/CICSTree.ts
- src/utils/profileManagement.ts
Fixes v1 profile functionalities including, delete, update, proceed with untrusted certificate, and load profile.
**Key change**: Call ProfilesCache refresh before loadNamedProfile
> Next v1 fix

- src/commands/closeLocalFileCommand.ts
- src/commands/disableLocalFileCommand.ts
- src/commands/disableProgramCommand.ts
- src/commands/disableTransactionCommand.ts
- src/commands/enableLocalFileCommand.ts
- src/commands/enableProgramCommand.ts
- src/commands/enableTransactionCommand.ts
- src/commands/newCopyCommand.ts
- src/commands/openLocalFileCommand.ts
- src/commands/phaseInCommand.ts
- src/trees/CICSCombinedLocalFileTree.ts
- src/trees/CICSCombinedProgramTree.ts
- src/trees/CICSCombinedTransactionTree.ts
- src/trees/CICSLocalFileTree.ts
- src/trees/CICSProgramTree.ts
- src/trees/CICSTransactionTree.ts
- src/trees/CICSTree.ts
- src/utils/expansionHandler.ts
Removed all the `@ts-ignore` calls.
> Remove ts ignore

- src/utils/webviewHTML.ts
> word wrap; fixes #233

- src/commands/closeLocalFileCommand.ts
- src/commands/disableTransactionCommand.ts
- src/commands/newCopyCommand.ts
- src/commands/openLocalFileCommand.ts
- src/commands/phaseInCommand.ts
- src/commands/purgeTaskCommand.ts
- src/utils/commandUtils.ts
> Code refactor

- src/commands/showAttributesCommand.ts
> all resource attributes fixed to have upper capitalization; fixes #238

- src/trees/CICSLocalFileTree.ts
- src/trees/CICSProgramTree.ts
- src/trees/CICSTaskTree.ts
- src/trees/CICSTransactionTree.ts
> Update label to be 0 if resource not found

- package-lock.json
- package.json
> version number updated to reflect 2.1.0 release

- src/commands/disableLibraryCommand.ts
> removed unnecessary console.log statements

- CHANGELOG.md
- README.md
- package.json
- src/commands/inquireProgram.ts
- src/commands/inquireTransaction.ts
- src/extension.ts
Signed-off-by: Adarshdeep Cheema <adarshdeep.cheema@ibm.com>
> rename Reveal to Inquire

- README.md
> minor fix for README.md text

- CHANGELOG.md
> minor fix for commandlog

- package.json
- src/commands/clearResourceFilterCommand.ts
- src/commands/filterDatasetsCommand.ts
- src/commands/filterProgramsCommand.ts
- src/extension.ts
- src/trees/treeItems/CICSLibraryDatasets.ts
- src/trees/treeItems/CICSLibraryTreeItem.ts
- src/utils/PersistentStorage.ts
> added programs under datasets; fixes #279, #271, #294

- README.md
- src/commands/purgeTaskCommand.ts
> removed the ability to kill a task; fixes #278

- src/commands/clearPlexFilterCommand.ts
- src/commands/getFilterPlexResources.ts
- src/trees/CICSCombinedLibraryTree.ts
- src/trees/CICSCombinedLocalFileTree.ts
- src/trees/CICSCombinedProgramTree.ts
- src/trees/CICSCombinedTaskTree.ts
- src/trees/CICSCombinedTransactionTree.ts
- src/trees/treeItems/CICSLibraryDatasets.ts
> filter fixes for resources; fixes #299, #297, #298

- src/utils/webviewHTML.ts
> aligned attribute items to center for consistency

- package-lock.json
- package.json
> updated version number
